<?php
// $Id$
/**
 * @file
 * CVS backend for Version Control API - Provides CVS commit information and
 * account management as a pluggable backend.
 *
 * Copyright 2007 by Jakob Petsovits ("jpetso", http://drupal.org/user/56020)
 */

// Update methods.
define('VERSIONCONTROL_CVS_UPDATE_CRON', 0);
define('VERSIONCONTROL_CVS_UPDATE_XCVS', 1);

// The admin pages.
include_once(drupal_get_path('module', 'versioncontrol_cvs') .'/versioncontrol_cvs.admin.inc');

/**
 * Implementation of hook_versioncontrol_backends().
 *
 * @return
 *   A structured array containing information about this known backends.
 *   Array key is the unique string identifier of the version control system.
 *   The corresponding array values are again structured arrays and consist
 *   of elements with the following keys:
 *
 *   'name': The user-visible name of the VCS.
 *   'description': A short description of the backend, if possible not longer
 *                  than one or two sentences.
 *   'capabilities': An array listing optional capabilities, in addition to the
 *                   required functionality like retrieval of detailed
 *                   commit information. Array values can be an arbitrary
 *                   combination of VERSIONCONTROL_CAPABILITY_* values. If no
 *                   additional capabilities are supported by the backend,
 *                   this array will be empty.
 *   'autoadd': An array listing which tables should be managed by
 *              Version Control API instead of doing it manually in
 *              the backend. Array values can be an arbitrary combination of
 *              VERSIONCONTROL_AUTOADD_* values. If no array additions
 *              should be automatically managed, this array will be empty.
 */
function versioncontrol_cvs_versioncontrol_backends() {
  return array(
    // The array key is up to 8 characters long, and used as unique identifier
    // for this VCS, in functions, URLs and in the database.
    'cvs' => array(
      // The user-visible name of the VCS.
      'name' => 'CVS',

      // A short description of the VCS, if possible not longer than one or two sentences.
      'description' => t('CVS (Concurrent Versions System) is a slightly older code management system that supports file revisions, tags and branches, but lacks atomic commits, advanced merge functionality and support for renaming items.'),

      // A list of optional capabilities, in addition to the required retrieval
      // of detailed commit information.
      'capabilities' => array(
        // Able to cancel commits if the committer lacks permissions
        // to commit to specific paths and/or branches.
        VERSIONCONTROL_CAPABILITY_COMMIT_RESTRICTIONS,
        // Able to cancel branch or tag assignments if the committer lacks
        // permissions to create/update/delete those.
        VERSIONCONTROL_CAPABILITY_BRANCH_TAG_RESTRICTIONS,
      ),

      // An array listing which tables should be managed by Version Control API
      // instead of doing it manually in the backend.
      'flags' => array(
        // versioncontrol_insert_repository() will automatically insert
        // array elements from $repository['cvs_specific'] into
        // {versioncontrol_cvs_repositories} and versioncontrol_get_repositories()
        // will automatically fetch it from there.
        VERSIONCONTROL_FLAG_AUTOADD_REPOSITORIES,
        // versioncontrol_insert_commit() will automatically insert
        // array elements from $commit['cvs_specific'] into
        // {versioncontrol_cvs_commits} and versioncontrol_get_commits()
        // will automatically fetch it from there.
        VERSIONCONTROL_FLAG_AUTOADD_COMMITS,
      ),
    ),
  );
}


/**
 * Implementation of [versioncontrol_backend]_get_commit_actions():
 * Retrieve detailed information about what happened in a single commit.
 *
 * @param $commit
 *   The commit whose actions should be retrieved.
 *
 * @return
 *   A structured array containing the exact details of what happened to
 *   each item in this commit. Array keys are the current/new paths, also for
 *   VERSIONCONTROL_ACTION_DELETED actions even if the file actually doesn't
 *   exist anymore. The corresponding array values are again structured arrays
 *   and consist of elements with the following keys:
 *
 *   'action': Specifies how the item was modified.
 *             One of the predefined VERSIONCONTROL_ACTION_* values.
 *   'modified': Boolean value, specifies if a file was modified in addition
 *               to the other action in the 'action' element of the array.
 *               Only exists for the VERSIONCONTROL_ACTION_MOVED
 *               and VERSIONCONTROL_ACTION_COPIED actions.
 *   'current item': The updated state of the modified item. Exists for all
 *                   actions except VERSIONCONTROL_ACTION_DELETED.
 *   'source items': An array with the previous state(s) of the modified item.
 *                   Path and branch will always be the same as in the current
 *                   item except for the VERSIONCONTROL_ACTION_MOVED,
 *                   VERSIONCONTROL_ACTION_COPIED and
 *                   VERSIONCONTROL_ACTION_MERGED actions.
 *                   Exists for all actions except VERSIONCONTROL_ACTION_ADDED.
 *
 *   Item values are structured arrays and consist of elements
 *   with the following keys:
 *
 *   'type': Specifies the item type, which is either
 *           VERSIONCONTROL_ITEM_FILE or VERSIONCONTROL_ITEM_DIRECTORY.
 *   'path': The path of the item at the specific revision.
 *   'revision': The (file-level) revision when the item was changed.
 *               If there is no such revision (which may be the case for
 *               directory items) then the 'revision' element is NULL.
 *   '[xxx]_specific': May be set by the backend to remember additional
 *                     item info. ("[xxx]" is the unique string identifier
 *                     of the respective version control system.)
 */
function versioncontrol_cvs_get_commit_actions($commit) {
  $actions = array();
  $result = db_query("SELECT * FROM {versioncontrol_cvs_item_revisions}
                      WHERE commit_id = '%d'", $commit['commit_id']);

  while ($item_revision = db_fetch_object($result)) {
    $action = array(
      'type' => $item_revision->action,
    );

    if ($item_revision->action != VERSIONCONTROL_ACTION_DELETED) {
      $action['current item'] = array(
        'type' => $item_revision->type,
        'path' => $item_revision->path,
        'revision' => $item_revision->revision,
        'cvs_specific' => array(
          'selected branch' => $commit['cvs_specific']['branch_id'],
          'selected date' => $commit['date'],
        ),
      );
    }
    if ($item_revision->action != VERSIONCONTROL_ACTION_ADDED) {
      $action['source items'] = array(array(
        'type' => $item_revision->type,
        'path' => $item_revision->path,
        'revision' => $item_revision->source_revision,
        'cvs_specific' => array(
          'selected branch' => $commit['cvs_specific']['branch_id'],
          'selected date' => $commit['date'],
        ),
      ));
    }

    $actions[$item_revision->path] = $action;
  }

  return $actions;
}

/**
 * Implementation of [versioncontrol_backend]_get_commit_directory_item():
 * Retrieve the item of the deepest-level directory in the repository that is
 * common to all the changed items in a commit. In other words, this function
 * gets you the item for $commit['directory'].
 *
 * @param $commit
 *   The commit whose deepest-level changed directory should be retrieved.
 *
 * @return
 *   The requested directory item. Item values are structured arrays and
 *   consist of elements with the following keys:
 *
 *   'type': Specifies the item type, which in this case can only be
 *           VERSIONCONTROL_ITEM_DIRECTORY.
 *   'path': The path of the directory at the time of the commit.
 *   'revision': The (file-level) revision when the item was last changed.
 *               If there is no such revision (which may be the case for
 *               directory items) then the 'revision' element is NULL.
 *   '[xxx]_specific': May be set by the backend to remember additional
 *                     item info. ("[xxx]" is the unique string identifier
 *                     of the respective version control system.)
 */
function versioncontrol_cvs_get_commit_directory_item($commit) {
  return array(
    'type' => VERSIONCONTROL_ITEM_DIRECTORY,
    'path' => $commit['directory'],
    'revision' => NULL,
    'cvs_specific' => array(
      'selected branch' => $commit['cvs_specific']['branch_id'],
      'selected date' => $commit['date'],
    ),
  );
}

/**
 * Implementation of [versioncontrol_backend]_get_commit_branches():
 * Retrieve the branches that have been affected by the given commit.
 *
 * @return
 *   An array of strings that identify a branch in the respective repository,
 *   or an empty array if no branches were affected at all. (For CVS, there
 *   should always be a exactly one branch in the resulting array.)
 */
function versioncontrol_cvs_get_commit_branches($commit) {
  if (!isset($commit['cvs_specific']['branch_id'])) {
    return array();
  }

  $branch = _versioncontrol_cvs_get_branch($commit['cvs_specific']['branch_id']);
  if (!isset($branch)) {
    return array(); // should only happen in case of database inconsistencies
  }
  return array($branch['name']);
  // TODO: improve so that all affected branches are returned.
}

/**
 * Implementation of [versioncontrol_backend]_get_current_item_branch():
 * Retrieve the current branch that this item is in. If this item was part of
 * the result of versioncontrol_get_commit_actions(), this will probably be
 * the branch that this item was committed to. If no specific branch is known
 * or applicable for this item, NULL is returned. The main branch ('HEAD'
 * for CVS) is also a valid branch and should be expected as return value.
 *
 * @param $repository
 *   The repository that the item is located in.
 * @param $item
 *   The item whose current branch should be retrieved.
 *
 * @return
 *   A string containing the current item branch, or NULL if no branch
 *   is known or applicable.
 */
function versioncontrol_cvs_get_current_item_branch($repository, $item) {
  if (!isset($item['cvs_specific']['selected branch'])) {
    return NULL;
  }

  $branch = _versioncontrol_cvs_get_branch($item['cvs_specific']['selected branch']);
  if (!isset($branch)) {
    return NULL;
  }
  return $branch['name'];
}

/**
 * Implementation of [versioncontrol_backend]_get_current_item_tag():
 * Retrieve the current tag that this item is in. If no specific tag is known
 * or applicable for this item, NULL is returned.
 *
 * @param $repository
 *   The repository that the item is located in.
 * @param $item
 *   The item whose current branch should be retrieved.
 *
 * @return
 *   A string containing the current item branch, or NULL if no tag
 *   is known or applicable.
 */
function versioncontrol_cvs_get_current_item_tag($repository, $item) {
  if (!isset($item['cvs_specific']['selected tag'])) {
    return NULL;
  }

  $tag = _versioncontrol_cvs_get_tag_operation($item['cvs_specific']['selected tag']);
  if (!isset($tag)) {
    return NULL;
  }
  return $tag['name'];
}


/**
 * Implementation of [versioncontrol_backend]_commit():
 * Manage (insert or delete) additional commit data in the database.
 *
 * @param $op
 *   Either 'insert' when the commit is in the process of being created,
 *   or 'delete' if it will be deleted after this function has been called.
 * @param $commit
 *   A single commit array, like the ones returned
 *   by versioncontrol_get_commits().
 * @param $commit_actions
 *   A structured array containing the exact details of what happened to
 *   each item in this commit. The structure of this array is the same as
 *   the return value of versioncontrol_get_commit_actions().
 */
function versioncontrol_cvs_commit($op, $commit, $commit_actions) {
  switch ($op) {
    case 'insert':
      foreach ($commit_actions as $path => $action) {
        $revision = '';
        $source_revision = '';

        // If available, get item type and revision from the contained items.
        if (isset($action['current item'])) {
          $type = $action['current item']['type'];
          $revision = $action['current item']['revision'];
        }
        if (isset($action['source items'])) {
          $type = $action['source items'][0]['type']; // only one source item for CVS
          $source_revision = $action['source items'][0]['revision'];
        }

        $item_revision_id = db_next_id('{versioncontrol_cvs_item_revisions}_item_revision_id');
        db_query(
          "INSERT INTO {versioncontrol_cvs_item_revisions}
           (item_revision_id, commit_id, type, path, revision,
            action, lines_added, lines_removed, source_revision)
           VALUES ('%d', '%d', '%d', '%s', '%s', '%d', '%d', '%d', '%s')",
          $item_revision_id, $commit['commit_id'], $type, $path, $revision,
          $action['action'], $action['cvs_specific']['lines_added'],
          $action['cvs_specific']['lines_removed'], $source_revision
        );
      }
      break;

    case 'delete':
      $result = db_query("SELECT item_revision_id
                          FROM {versioncontrol_cvs_item_revisions}
                          WHERE commit_id = '%d'", $commit['commit_id']);

      while ($revision = db_fetch_object($result)) {
        db_query("DELETE FROM {versioncontrol_cvs_item_tags}
                  WHERE item_revision_id = '%d'",
                  $revision->item_revision_id);
      }
      db_query("DELETE FROM {versioncontrol_cvs_item_revisions}
                WHERE commit_id = '%d'", $commit['commit_id']);
      break;
  }
}

/**
 * Implementation of [versioncontrol_backend]_account():
 * Manage (insert, update or delete) additional CVS user account data
 * in the database.
 *
 * @param $op
 *   Either 'insert' when the account is in the process of being created,
 *   or 'update' when username or additional module data change,
 *   or 'delete' if it will be deleted after this function has been called.
 * @param $uid
 *   The Drupal user id corresponding to the VCS account.
 * @param $username
 *   The VCS specific username (a string).
 * @param $repository
 *   The repository where the user has its VCS account.
 * @param $additional_data
 *   An array of additional author information.
 */
function versioncontrol_cvs_account($op, $uid, $username, $repository, $additional_data = array()) {
  $cvs_specific = $additional_data['cvs_specific'];

  switch ($op) {
    case 'insert':
      if (!isset($cvs_specific) || !isset($cvs_specific['password'])) {
        drupal_set_message(t('Error: no CVS password given on account creation!'), 'error');
        return;
      }
      db_query("INSERT INTO {versioncontrol_cvs_accounts}
                (uid, repo_id, password)
                VALUES ('%d', '%d', '%s')",
                $uid, $repository['repo_id'], $cvs_specific['password']);
      break;

    case 'update':
      if (!isset($cvs_specific) || !isset($cvs_specific['password'])) {
        return; // the user didn't update the password in the process.
      }
      db_query("UPDATE {versioncontrol_cvs_accounts}
                SET password = '%s'
                WHERE uid = '%d' AND repo_id = '%d'",
                $cvs_specific['password'], $uid, $repository['repo_id']);

      if (!user_access('administer version control systems')) {
        // Admins get "The account has been updated successfully" anyways.
        drupal_set_message(t('The CVS password has been updated successfully.'));
      }
      break;

    case 'delete':
      db_query("DELETE FROM {versioncontrol_cvs_accounts}
                WHERE uid = '%d' AND repo_id = '%d'",
                $uid, $repository['repo_id']);
      break;
  }
}

/**
 * Implementation of [versioncontrol_backend]_repository():
 * Manage (insert, update or delete) additional CVS repository data
 * in the database.
 *
 * @param $op
 *   Either 'insert' when the repository has just been created, or 'update'
 *   when repository name, root, URL backend or module specific data change,
 *   or 'delete' if it will be deleted after this function has been called.
 *
 * @param $repository
 *   The repository array containing the repository. It's a single
 *   repository array like the one returned by versioncontrol_get_repository(),
 *   so it consists of the following elements:
 *
 *   'repo_id': The unique repository id.
 *   'name': The user-visible name of the repository.
 *   'vcs': The unique string identifier of the version control system
 *          that powers this repository.
 *   'root': The root directory of the repository. In most cases,
 *           this will be a local directory (e.g. '/var/repos/drupal'),
 *           but it may also be some specialized string for remote repository
 *           access. How this string may look like depends on the backend.
 *   'url_backend': The prefix (excluding the trailing underscore)
 *                  for URL backend retrieval functions.
 *   '[xxx]_specific': An array of VCS specific additional repository
 *                     information. How this array looks like is defined by the
 *                     corresponding backend module (versioncontrol_[xxx]).
 */
function versioncontrol_cvs_repository($op, $repository) {
  if ($op == 'delete') {
    // Repository ids are not given for branch operations, so we need to
    // retrieve the branch ids in order to delete the branch ops.
    $result = db_query("SELECT branch_id FROM {versioncontrol_cvs_branches}
                        WHERE ". implode(' OR ', $repo_id_constraints), $repo_ids);
    $branch_ids = array();
    $branch_id_constraints = array();
    while ($branch = db_fetch_object($result)) {
      $branch_id_constraints[] = "branch_id = '%d'";
      $branch_ids[] = $branch->branch_id;
    }
    if (!empty($branch_ids)) {
      db_query("DELETE FROM {versioncontrol_cvs_branch_operations}
                WHERE ". implode(' OR ', $branch_id_constraints), $branch_ids);
    }
    // The other ones can be deleted by specifying the repository id.
    db_query("DELETE FROM {versioncontrol_cvs_branches}
              WHERE repo_id = '%d'", $repository['repo_id']);
    db_query("DELETE FROM {versioncontrol_cvs_tag_operations}
              WHERE repo_id = '%d'", $repository['repo_id']);
  }
}

/**
 * Insert a branch into the {versioncontrol_cvs_branches} table.
 * No checking is done whether the branch already exists or not.
 *
 * @return
 *   The branch id of the newly inserted branch entry.
 */
function _versioncontrol_cvs_insert_branch($branch_name, $repo_id) {
  $branch_id = db_next_id('{versioncontrol_cvs_branches}_branch_id');
  db_query("INSERT INTO {versioncontrol_cvs_branches} (branch_id, repo_id, name)
            VALUES ('%d', '%d', '%s')", $branch_id, $repo_id, $name);
  return $branch_id;
}

/**
 * Insert branched items into the database.
 */
function _versioncontrol_cvs_insert_branch_operation($branch, $branched_items) {
  if (empty($branch['items'])) {
    return;
  }
  $branch_op_id = db_next_id('{versioncontrol_cvs_branch_operations}_branch_op_id');
  db_query("INSERT INTO {versioncontrol_cvs_branch_operations}
            (branch_op_id, branch_id, date)
            VALUES ('%d', '%d', '%d')",
            $branch_op_id, $branch['branch_id'], time());

  foreach ($branched_items as $item) {
    $result = db_query("SELECT item_revision_id
                        FROM {versioncontrol_cvs_item_revisions}
                        WHERE path = '%s' AND revision = '%s'",
                        $item['path'], $item['revision']);

    while ($revision = db_fetch_object($result)) {
      db_query("INSERT INTO {versioncontrol_cvs_item_branch_points}
                (branch_op_id, item_revision_id)
                VALUES ('%d', '%d')",
                $branch_op_id, $revision->item_revision_id);
    }
  }
}

/**
 * Retrieve the branch name and repository for a given branch id.
 *
 * @return
 *   A structured array consisting of the 'branch_id, 'repo_id' and 'name'
 *   elements, or NULL if there is no branch for this branch id.
 */
function _versioncontrol_cvs_get_branch($branch_id) {
  static $branch_cache = array();

  if (isset($branch_cache[$branch_id])) {
    if ($branch_cache[$branch_id] === FALSE) {
      return NULL; // there's no branch for this id
    }
    return $branch_cache[$branch_id]; // return the cached branch array
  }

  $result = db_query("SELECT branch_id, repo_id, name
                      FROM {versioncontrol_cvs_branches}
                      WHERE branch_id = '%d'", $branch_id);

  while ($branch = db_fetch_array($result)) {
    $branch_cache[$branch_id] = $branch;
    return $branch;
  }
  $branch_cache[$branch_id] = FALSE;
  return NULL;
}

/**
 * Retrieve the branch id for a given branch name from a specific repository.
 *
 * @return
 *   The branch id of the requested branch, or NULL if there is no branch
 *   for this name and repository.
 */
function _versioncontrol_cvs_get_branch_id($branch_name, $repo_id) {
  static $branch_cache = array();

  if (isset($branch_cache[$repo_id][$branch_name])) {
    if ($branch_cache[$repo_id][$branch_name] === FALSE) {
      return NULL; // there's no branch for this name and repository
    }
    return $branch_cache[$repo_id][$branch_name]; // return the cached branch id
  }

  $result = db_query("SELECT branch_id
                      FROM {versioncontrol_cvs_branches}
                      WHERE repo_id = '%d' AND name = '%s'",
                      $repo_id, $branch_name);

  while ($branch = db_fetch_object($result)) {
    $branch_cache[$repo_id][$branch_name] = $branch->branch_id;
    return $branch->branch_id;
  }
  $branch_cache[$repo_id][$branch_name] = FALSE;
  return NULL;
}


/**
 * Insert a tag operation into the database.
 *
 * @return
 *   The tag id of the newly inserted tag entry.
 */
function _versioncontrol_cvs_insert_tag_operation($tag, $tagged_items) {
  if (empty($tagged_items)) {
    return;
  }
  $tag_op_id = db_next_id('{versioncontrol_cvs_tag_operations}_tag_op_id');
  db_query("INSERT INTO {versioncontrol_cvs_tag_operations}
            (tag_op_id, repo_id, name, date)
            VALUES ('%d', '%d', '%s', '%d')",
            $tag_op_id, $tag['repo_id'], $tag['name'], time());

  foreach ($tagged_items as $item) {
    $result = db_query("SELECT item_revision_id
                        FROM {versioncontrol_cvs_item_revisions}
                        WHERE path = '%s' AND revision = '%s'",
                        $item['path'], $item['revision']);

    while ($revision = db_fetch_object($result)) {
      db_query("INSERT INTO {versioncontrol_cvs_item_tags}
                (tag_op_id, item_revision_id)
                VALUES ('%d', '%d')",
                $tag_op_id, $revision->item_revision_id);
    }
  }
}

/**
 * Retrieve the tag name, repository and timespamp for a given tag op id.
 *
 * @return
 *   A structured array consisting of the 'tag_id, 'repo_id', 'name' and 'date'
 *   elements, or NULL if there is no tag for this tag op id.
 */
function _versioncontrol_cvs_get_tag_operation($tag_op_id) {
  static $tag_cache = array();

  if (isset($tag_cache[$tag_op_id])) {
    if ($tag_cache[$tag_op_id] === FALSE) {
      return NULL; // there's no tag operation for this id
    }
    return $tag_cache[$tag_op_id]; // return the cached tag operation array
  }

  $result = db_query("SELECT tag_op_id, repo_id, name, date
                      FROM {versioncontrol_cvs_tag_operations}
                      WHERE tag_op_id = '%d'", $tag_op_id);

  while ($tag_operation = db_fetch_array($result)) {
    $tag_cache[$tag_op_id] = $tag_operation;
    return $tag_operation;
  }
  $tag_cache[$tag_op_id] = FALSE;
  return NULL;
}
